# Customer Churn Prediction
This project aims to predict whether a telecom customer is likely to discontinue the company's services using supervised machine learning techniques. By analyzing customer demographics, subscription details, billing information, and service usage, the model estimates the probability of customer churn before it occurs. The insights can help telecom companies improve customer retention strategies.

In [101]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
# # !pip install plotly

# import plotly.express as px

In [102]:
df = pd.read_csv(r"C:\Users\jestu\OneDrive\Desktop\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [103]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [104]:
df.shape

(7043, 21)

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [106]:
df.describe

<bound method NDFrame.describe of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 21 columns]>

In [107]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

## Data Cleaning

In [108]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [109]:
(df == " ").sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [110]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [111]:
df.dropna(inplace=True)

In [112]:
df.duplicated().sum()

0

In [113]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [114]:
df.drop("customerID", axis=1, inplace=True)

In [115]:
df.shape

(7032, 20)

In [116]:
df["Churn"].value_counts()

No     5163
Yes    1869
Name: Churn, dtype: int64

In [117]:
df["Churn"].value_counts(normalize=True) * 100  #This will help understand whether the dataset is balanced

No     73.421502
Yes    26.578498
Name: Churn, dtype: float64

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   object
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

# Exploratory Data Analysis (EDA)

In [119]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

plt.style.use("ggplot")

In [120]:
import plotly.express as px

fig = px.histogram(
    df,
    x="Churn",
    color="Churn",
    title="Customer Churn Distribution",
    text_auto=True
)

fig.update_layout(template="plotly_white")

fig.show()

In [121]:
# Most customers stayed with the company.
# A smaller percentage of customers churned.
# The dataset is moderately imbalanced, so evaluation metrics like Precision, Recall, F1-Score, and ROC-AUC will be more informative than accuracy alone.

In [122]:
fig = px.histogram(
    df,
    x="Contract",
    color="Churn",
    barmode="group",
    title="Contract Type vs Customer Churn"
)

fig.update_layout(template="plotly_white")

fig.show()

In [123]:
fig = px.box(
    df,
    x="Churn",
    y="tenure",
    color="Churn",
    title="Customer Tenure vs Churn"
)

fig.update_layout(template="plotly_white")

fig.show()

In [124]:
fig = px.box(
    df,
    x="Churn",
    y="MonthlyCharges",
    color="Churn",
    title="Monthly Charges vs Churn"
)

fig.update_layout(template="plotly_white")

fig.show()

In [125]:
fig = px.histogram(
    df,
    x="InternetService",
    color="Churn",
    barmode="group",
    title="Internet Service vs Churn"
)

fig.update_layout(template="plotly_white")

fig.show()

In [126]:
fig = px.histogram(
    df,
    x="PaymentMethod",
    color="Churn",
    barmode="group",
    title="Payment Method vs Churn"
)

fig.update_layout(
    template="plotly_white",
    xaxis_tickangle=-30
)

fig.show()

In [127]:
df_corr = df.copy()

df_corr["Churn"] = df_corr["Churn"].map({
    "No":0,
    "Yes":1
})

In [128]:
corr = df_corr.select_dtypes(include=["int64","float64"]).corr()

In [129]:
import plotly.express as px

fig = px.imshow(
    corr,
    text_auto=True,
    color_continuous_scale="RdBu_r",
    title="Correlation Heatmap"
)

fig.show()

## Business Insights

1. Customers with Month-to-Month contracts have the highest churn.

2. Customers with shorter tenure are more likely to leave.

3. Higher monthly charges are associated with higher churn.

4. Internet service type influences customer churn.

5. Payment method shows noticeable differences in churn behavior.

# Feature Engineering

In [130]:
# Customer Life time value - CLV = MonthlyCharges × tenure

df["CustomerLifetimeValue"] = df["MonthlyCharges"] * df["tenure"]

In [131]:
df["AverageMonthlySpend"] = df["TotalCharges"] / (df["tenure"] + 1)

In [132]:
service_columns = [
    "PhoneService",
    "MultipleLines",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies"
]

df["TotalServices"] = df[service_columns].apply(
    lambda x: (x == "Yes").sum(),
    axis=1
)

In [133]:
df["LongTermCustomer"] = (df["tenure"] >= 24).astype(int)

In [134]:
df["MonthlyContract"] = (
    df["Contract"] == "Month-to-month"
).astype(int)

In [135]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerLifetimeValue,AverageMonthlySpend,TotalServices,LongTermCustomer,MonthlyContract
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,Yes,Electronic check,29.85,29.85,No,29.85,14.925000,1,0,1
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,Mailed check,56.95,1889.50,No,1936.30,53.985714,3,1,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,Yes,Mailed check,53.85,108.15,Yes,107.70,36.050000,3,0,1
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,No,Bank transfer (automatic),42.30,1840.75,No,1903.50,40.016304,3,1,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,Yes,Electronic check,70.70,151.65,Yes,141.40,50.550000,1,0,1

In [136]:
import plotly.express as px

fig = px.box(
    df,
    x="Churn",
    y="CustomerLifetimeValue",
    color="Churn",
    title="Customer Lifetime Value vs Churn"
)

fig.show()

In [137]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn', 'CustomerLifetimeValue',
       'AverageMonthlySpend', 'TotalServices', 'LongTermCustomer',
       'MonthlyContract'],
      dtype='object')

In [138]:
df.to_csv("customer_churn_feature_engineered.csv", index=False)

# Data Preprocessing

In [139]:
df.dtypes

gender                    object
SeniorCitizen              int64
Partner                   object
Dependents                object
tenure                     int64
PhoneService              object
MultipleLines             object
InternetService           object
OnlineSecurity            object
OnlineBackup              object
DeviceProtection          object
TechSupport               object
StreamingTV               object
StreamingMovies           object
Contract                  object
PaperlessBilling          object
PaymentMethod             object
MonthlyCharges           float64
TotalCharges             float64
Churn                     object
CustomerLifetimeValue    float64
AverageMonthlySpend      float64
TotalServices              int64
LongTermCustomer           int32
MonthlyContract            int32
dtype: object

In [140]:
df["Churn"] = df["Churn"].map({
    "No":0,
    "Yes":1
})

In [141]:
df["Churn"].value_counts()

0    5163
1    1869
Name: Churn, dtype: int64

In [142]:
categorical_columns = df.select_dtypes(include="object").columns

categorical_columns

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

In [143]:
df = pd.get_dummies(
    df,
    columns=categorical_columns,
    drop_first=True
)

In [144]:
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,CustomerLifetimeValue,AverageMonthlySpend,TotalServices,LongTermCustomer,MonthlyContract,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,29.85,14.925000,1,0,1,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,0,1936.30,53.985714,3,1,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,107.70,36.050000,3,0,1,...,0,0,0,0,0,0,1,0,0,1
3,0,45,42.30,1840.75,0,1903.50,40.016304,3,1,0,...,0,0,0,0,1,0,0,0,0,0
4,0,2,70.70,151.65,1,141.40,50.550000,1,0,1,...,0,0,0,0,0,0,1,0,1,0

In [145]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

In [146]:
print(X.shape)

print(y.shape)

(7032, 35)
(7032,)

In [147]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [148]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Target   :", y_train.shape)
print("Testing Target    :", y_test.shape)

Training Features : (5625, 35)
Testing Features  : (1407, 35)
Training Target   : (5625,)
Testing Target    : (1407,)

In [149]:
print(y_train.value_counts(normalize=True))

print(y_test.value_counts(normalize=True))

0    0.734222
1    0.265778
Name: Churn, dtype: float64
0    0.734186
1    0.265814
Name: Churn, dtype: float64

# Model Training & Comparison

In [150]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

In [151]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [152]:
log_model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

log_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [153]:
log_prob = log_model.predict_proba(X_test_scaled)[:, 1]
threshold = 0.38

log_pred = (log_prob >= threshold).astype(int)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy :", accuracy_score(y_test, log_pred))
print("Precision:", precision_score(y_test, log_pred))
print("Recall   :", recall_score(y_test, log_pred))
print("F1 Score :", f1_score(y_test, log_pred))

print("ROC-AUC  :", roc_auc_score(y_test, log_prob))

Accuracy : 0.7839374555792467
Precision: 0.5770925110132159
Recall   : 0.7005347593582888
F1 Score : 0.6328502415458938
ROC-AUC  : 0.8375467849728997

In [154]:
log_accuracy = accuracy_score(y_test, log_pred)
log_precision = precision_score(y_test, log_pred)
log_recall = recall_score(y_test, log_pred)
log_f1 = f1_score(y_test, log_pred)
log_auc = roc_auc_score(y_test, log_pred)

print("Accuracy :", log_accuracy)
print("Precision:", log_precision)
print("Recall   :", log_recall)
print("F1 Score :", log_f1)
print("ROC AUC  :", log_auc)

Accuracy : 0.7839374555792467
Precision: 0.5770925110132159
Recall   : 0.7005347593582888
F1 Score : 0.6328502415458938
ROC AUC  : 0.7573341754197059

In [155]:
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

In [156]:
rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)
rf_auc = roc_auc_score(y_test, rf_pred)

print("Accuracy :", rf_accuracy)
print("Precision:", rf_precision)
print("Recall   :", rf_recall)
print("F1 Score :", rf_f1)
print("ROC AUC  :", rf_auc)

Accuracy : 0.7853589196872779
Precision: 0.62
Recall   : 0.49732620320855614
F1 Score : 0.5519287833827894
ROC AUC  : 0.6934840115752364

In [157]:
xgb_model = XGBClassifier(
    random_state=42,
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    eval_metric="logloss"
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)

In [158]:
xgb_accuracy = accuracy_score(y_test, xgb_pred)
xgb_precision = precision_score(y_test, xgb_pred)
xgb_recall = recall_score(y_test, xgb_pred)
xgb_f1 = f1_score(y_test, xgb_pred)
xgb_auc = roc_auc_score(y_test, xgb_pred)

print("Accuracy :", xgb_accuracy)
print("Precision:", xgb_precision)
print("Recall   :", xgb_recall)
print("F1 Score :", xgb_f1)
print("ROC AUC  :", xgb_auc)

Accuracy : 0.7917555081734187
Precision: 0.6253869969040248
Recall   : 0.5401069518716578
F1 Score : 0.5796269727403157
ROC AUC  : 0.7114861961681619

In [159]:
comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        log_accuracy,
        rf_accuracy,
        xgb_accuracy
    ],
    "Precision": [
        log_precision,
        rf_precision,
        xgb_precision
    ],
    "Recall": [
        log_recall,
        rf_recall,
        xgb_recall
    ],
    "F1 Score": [
        log_f1,
        rf_f1,
        xgb_f1
    ],
    "ROC-AUC": [
        log_auc,
        rf_auc,
        xgb_auc
    ]
})

comparison

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0  Logistic Regression  0.783937   0.577093  0.700535  0.632850  0.757334
1        Random Forest  0.785359   0.620000  0.497326  0.551929  0.693484
2              XGBoost  0.791756   0.625387  0.540107  0.579627  0.711486

# Model Evaluation

In [160]:
from sklearn.metrics import classification_report

print(classification_report(y_test, log_pred))

              precision    recall  f1-score   support

           0       0.88      0.81      0.85      1033
           1       0.58      0.70      0.63       374

    accuracy                           0.78      1407
   macro avg       0.73      0.76      0.74      1407
weighted avg       0.80      0.78      0.79      1407

In [161]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, log_pred)

cm

array([[841, 192],
       [112, 262]], dtype=int64)

In [162]:
import plotly.express as px

fig = px.imshow(
    cm,
    text_auto=True,
    color_continuous_scale="Blues",
    labels=dict(x="Predicted", y="Actual"),
    x=["No Churn","Churn"],
    y=["No Churn","Churn"],
    title="Confusion Matrix"
)

fig.show()

In [163]:
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": log_model.coef_[0]
})

importance["Absolute"] = importance["Coefficient"].abs()

importance = importance.sort_values(
    by="Absolute",
    ascending=False
)

In [164]:
importance.head(15)

                           Feature  Coefficient  Absolute
5              AverageMonthlySpend    -1.211114  1.211114
3                     TotalCharges     0.996024  0.996024
15     InternetService_Fiber optic     0.947896  0.947896
1                           tenure    -0.922439  0.922439
4            CustomerLifetimeValue    -0.441966  0.441966
30               Contract_Two year    -0.396085  0.396085
8                  MonthlyContract     0.370177  0.370177
26                 StreamingTV_Yes     0.312474  0.312474
2                   MonthlyCharges    -0.312272  0.312272
28             StreamingMovies_Yes     0.306464  0.306464
14               MultipleLines_Yes     0.257564  0.257564
6                    TotalServices     0.182992  0.182992
33  PaymentMethod_Electronic check     0.160417  0.160417
31            PaperlessBilling_Yes     0.140318  0.140318
18              OnlineSecurity_Yes    -0.114043  0.114043

In [181]:
customer_index = 1405

probability = probabilities[customer_index]

if probability >= 0.70:
    risk = "🔴 High Risk"
elif probability >= 0.40:
    risk = "🟡 Medium Risk"
else:
    risk = "🟢 Low Risk"

prediction = (
    "Likely to Churn"
    if probability >= threshold
    else "Not Likely to Churn"
)

print("=" * 40)
print(f"Customer Index      : {customer_index}")
print(f"Churn Probability   : {probability * 100:.2f}%")
print(f"Prediction          : {prediction}")
print(f"Risk Level          : {risk}")
print("=" * 40)

========================================
Customer Index      : 1405
Churn Probability   : 2.26%
Prediction          : Not Likely to Churn
Risk Level          : 🟢 Low Risk
========================================

In [182]:
import joblib

joblib.dump(log_model, "churn_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(threshold, "threshold.pkl")
joblib.dump(list(X_train.columns), "feature_names.pkl")

['feature_names.pkl']

In [183]:
import os

print(os.getcwd())

C:\Users\jestu